apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hermes
  namespace: pipenodes
  labels:
    app: hermes
spec:
  ingressClassName: traefik
  rules:
    - host: llm-gateway.pipenodes.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hermes
                port:
                  number: 8080
