apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipenodes
resources:
  - namespace.yaml
  - secrets.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
images:
  - name: pipenodes/llm-gateway
    newName: ghcr.io/pipeleap/llm-gateway
    newTag: "2.0"
